"""Replay harness for CLI/API case validation against the oracle."""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib import request

from scripts.golden_answers import build as build_oracle


@dataclass(frozen=True)
class ReplaySpec:
    case_id: str
    question: str
    expected_intent_types: tuple[str, ...]
    required_tools: tuple[str, ...] = ()
    required_bound_tools: tuple[str, ...] = ()
    required_trace_kinds: tuple[str, ...] = ()
    required_text: tuple[str, ...] = ()
    required_numbers: tuple[float, ...] = ()
    number_tolerance: float = 0.05
    expected_stop_reason: str = "final_answer"
    require_structured_tool_results: bool = False


@dataclass(frozen=True)
class CheckResult:
    name: str
    ok: bool
    detail: str


@dataclass(frozen=True)
class ReplayTurnSpec:
    turn_id: str
    question: str
    expected_intent_types: tuple[str, ...]
    required_tools: tuple[str, ...] = ()
    required_bound_tools: tuple[str, ...] = ()
    required_trace_kinds: tuple[str, ...] = ()
    required_text: tuple[str, ...] = ()
    required_numbers: tuple[float, ...] = ()
    number_tolerance: float = 0.05
    expected_stop_reason: str = "final_answer"
    require_structured_tool_results: bool = False
    require_prior_answer_verdict: bool = False
    required_prior_answer_verdict_text: tuple[str, ...] = ()
    required_prior_answer_verdict_numbers: tuple[float, ...] = ()
    deferred_assertions: tuple[str, ...] = ()


@dataclass(frozen=True)
class MultiTurnReplaySpec:
    transcript_id: str
    title: str
    turns: tuple[ReplayTurnSpec, ...]
    notes: tuple[str, ...] = ()


def build_replay_specs() -> dict[str, ReplaySpec]:
    return {
        "D2": ReplaySpec(
            case_id="D2",
            question="What was the average daily yield of Rajasthan Solar Park last week?",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(123354.2,),
        ),
        "D3": ReplaySpec(
            case_id="D3",
            question="Which inverters have open hotspot anomalies caused by soiling?",
            expected_intent_types=("C",),
            required_tools=("anomalies",),
            required_text=("hotspot", "soiling"),
            required_numbers=(2.0, 7.0, 55.0),
        ),
        "D4": ReplaySpec(
            case_id="D4",
            question="What is the mean time to resolve a critical alert?",
            expected_intent_types=("B",),
            required_numbers=(6.3, 6.0),
        ),
        "D5": ReplaySpec(
            case_id="D5",
            question="What's the weather like at the Gujarat plant today?",
            expected_intent_types=("A", "B"),
            required_text=("gujarat",),
            required_numbers=(26.04, 46.24, 799.34),
        ),
        "D6": ReplaySpec(
            case_id="D6",
            question="How much revenue did we lose from Tamil Nadu's downtime this month?",
            expected_intent_types=(),
            required_text=("can't answer", "dataset"),
            expected_stop_reason="out_of_scope",
        ),
        "P4": ReplaySpec(
            case_id="P4",
            question="Which plant has the highest feed-in tariff?",
            expected_intent_types=("B",),
            required_bound_tools=("inverters", "plants"),
            required_text=("rajasthan",),
            required_numbers=(0.052,),
        ),
        "I5": ReplaySpec(
            case_id="I5",
            question='Show inverters that are "online" in status but have an open alert.',
            expected_intent_types=("A",),
            required_text=("inv_4135001_05",),
            required_numbers=(4.0,),
        ),
        "G2": ReplaySpec(
            case_id="G2",
            question="Total energy generated by Rajasthan this month.",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(3004224.3,),
        ),
        "G4": ReplaySpec(
            case_id="G4",
            question="Which inverter tops the fleet on performance ratio?",
            expected_intent_types=("B",),
            required_text=("inv_4137001_04",),
            required_numbers=(0.9519,),
        ),
        "W3": ReplaySpec(
            case_id="W3",
            question="Which plant had the highest cloud cover this month?",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(23.66,),
        ),
        "AL5": ReplaySpec(
            case_id="AL5",
            question="Mean time to resolve an alert, all severities.",
            expected_intent_types=("B",),
            required_numbers=(22.16, 25.0),
        ),
        "AN6": ReplaySpec(
            case_id="AN6",
            question="Give me a rundown of every unresolved anomaly at Rajasthan Solar Park.",
            expected_intent_types=("C",),
            required_bound_tools=("anomalies", "inverters", "plants"),
            required_trace_kinds=("intent_finished", "synthesis_started", "model_invoke_started"),
            required_text=("rajasthan",),
            required_numbers=(15.0, 7.0, 5.0, 3.0),
            require_structured_tool_results=True,
        ),
        "X2": ReplaySpec(
            case_id="X2",
            question="Compare Rajasthan and Tamil Nadu on open anomalies and yield.",
            expected_intent_types=("B", "C"),
            required_text=("rajasthan", "tamil"),
            required_numbers=(7.0, 13.0, 123354.2, 151152.5),
        ),
        "X4": ReplaySpec(
            case_id="X4",
            question="Which plant is performing worst right now?",
            expected_intent_types=("B",),
            required_bound_tools=("performance_ratio", "inverters", "plants"),
            required_text=("rajasthan",),
            required_numbers=(0.9077,),
        ),
        "X6": ReplaySpec(
            case_id="X6",
            question="How is the plant doing?",
            expected_intent_types=(),
            required_text=("which plant",),
        ),
    }


def extract_numbers(text: str) -> list[float]:
    return [float(match.replace(",", "")) for match in re.findall(r"-?\d[\d,]*\.?\d*", text)]


def extract_numbers_from_value(value: Any) -> list[float]:
    if isinstance(value, bool):
        return []
    if isinstance(value, (int, float)):
        return [float(value)]
    if isinstance(value, str):
        return extract_numbers(value)
    if isinstance(value, dict):
        numbers: list[float] = []
        for nested in value.values():
            numbers.extend(extract_numbers_from_value(nested))
        return numbers
    if isinstance(value, (list, tuple)):
        numbers: list[float] = []
        for nested in value:
            numbers.extend(extract_numbers_from_value(nested))
        return numbers
    return []


def contains_subsequence(actual: list[str], required: tuple[str, ...]) -> bool:
    if not required:
        return True
    index = 0
    for item in actual:
        if item == required[index]:
            index += 1
            if index == len(required):
                return True
    return False


def replay_spec_from_mapping(case_id: str, payload: dict[str, Any]) -> ReplaySpec:
    return ReplaySpec(
        case_id=case_id,
        question=str(payload["question"]),
        expected_intent_types=tuple(str(value) for value in payload.get("expected_intent_types", ())),
        required_tools=tuple(str(value) for value in payload.get("required_tools", ())),
        required_bound_tools=tuple(str(value) for value in payload.get("required_bound_tools", ())),
        required_trace_kinds=tuple(str(value) for value in payload.get("required_trace_kinds", ())),
        required_text=tuple(str(value) for value in payload.get("required_text", ())),
        required_numbers=tuple(float(value) for value in payload.get("required_numbers", ())),
        number_tolerance=float(payload.get("number_tolerance", 0.05)),
        expected_stop_reason=str(payload.get("expected_stop_reason", "final_answer")),
        require_structured_tool_results=bool(payload.get("require_structured_tool_results", False)),
    )


def multi_turn_fixtures_dir() -> Path:
    return Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "multi_turn"


def load_multi_turn_spec(path: str | Path) -> MultiTurnReplaySpec:
    fixture_path = Path(path)
    raw = json.loads(fixture_path.read_text(encoding="utf-8"))
    transcript_id = str(raw["transcript_id"])
    title = str(raw["title"])
    turns_payload = raw.get("turns")
    if not isinstance(turns_payload, list) or not turns_payload:
        raise ValueError(f"{fixture_path} must define a non-empty turns list")
    turns: list[ReplayTurnSpec] = []
    for index, turn_payload in enumerate(turns_payload, start=1):
        spec = replay_spec_from_mapping(f"{transcript_id}:{index}", turn_payload)
        turns.append(
            ReplayTurnSpec(
                turn_id=str(turn_payload.get("turn_id", f"turn-{index}")),
                question=spec.question,
                expected_intent_types=spec.expected_intent_types,
                required_tools=spec.required_tools,
                required_bound_tools=spec.required_bound_tools,
                required_trace_kinds=spec.required_trace_kinds,
                required_text=spec.required_text,
                required_numbers=spec.required_numbers,
                number_tolerance=spec.number_tolerance,
                expected_stop_reason=spec.expected_stop_reason,
                require_structured_tool_results=spec.require_structured_tool_results,
                require_prior_answer_verdict=bool(turn_payload.get("require_prior_answer_verdict", False)),
                required_prior_answer_verdict_text=tuple(
                    str(value) for value in turn_payload.get("required_prior_answer_verdict_text", ())
                ),
                required_prior_answer_verdict_numbers=tuple(
                    float(value) for value in turn_payload.get("required_prior_answer_verdict_numbers", ())
                ),
                deferred_assertions=tuple(
                    str(value) for value in turn_payload.get("deferred_assertions", ())
                ),
            )
        )
    return MultiTurnReplaySpec(
        transcript_id=transcript_id,
        title=title,
        turns=tuple(turns),
        notes=tuple(str(value) for value in raw.get("notes", ())),
    )


def build_multi_turn_specs(fixtures_dir: str | Path | None = None) -> dict[str, MultiTurnReplaySpec]:
    root = Path(fixtures_dir) if fixtures_dir is not None else multi_turn_fixtures_dir()
    if not root.exists():
        return {}
    specs: dict[str, MultiTurnReplaySpec] = {}
    for path in sorted(root.glob("*.json")):
        spec = load_multi_turn_spec(path)
        specs[spec.transcript_id] = spec
    return specs


def evaluate_payload(spec: ReplaySpec, payload: dict[str, Any]) -> list[CheckResult]:
    answer = str(payload.get("answer", ""))
    answer_lower = answer.lower()
    tool_names = [str(call.get("name", "")) for call in payload.get("tool_calls", [])]
    bound_tools = [str(name) for name in payload.get("bound_tools", [])]
    trace_kinds = [str(event.get("kind", "")) for event in payload.get("trace_events", [])]
    actual_types = tuple(str(v) for v in payload.get("intent", {}).get("types", []))
    actual_numbers = extract_numbers(answer)

    checks = [
        CheckResult(
            name="stop_reason",
            ok=str(payload.get("stop_reason", "")) == spec.expected_stop_reason,
            detail=f"expected {spec.expected_stop_reason}, got {payload.get('stop_reason', '')}",
        ),
        CheckResult(
            name="intent_types",
            ok=all(intent_type in actual_types for intent_type in spec.expected_intent_types),
            detail=f"expected at least {list(spec.expected_intent_types)}, got {list(actual_types)}",
        ),
        CheckResult(
            name="tool_chain",
            ok=contains_subsequence(tool_names, spec.required_tools),
            detail=f"expected subsequence {list(spec.required_tools)}, got {tool_names}",
        ),
        CheckResult(
            name="bound_tools",
            ok=contains_subsequence(bound_tools, spec.required_bound_tools),
            detail=f"expected subsequence {list(spec.required_bound_tools)}, got {bound_tools}",
        ),
        CheckResult(
            name="trace_kinds",
            ok=contains_subsequence(trace_kinds, spec.required_trace_kinds),
            detail=f"expected subsequence {list(spec.required_trace_kinds)}, got {trace_kinds}",
        ),
    ]
    if spec.require_structured_tool_results:
        malformed = [
            str(call.get("name", ""))
            for call in payload.get("tool_calls", [])
            if not isinstance(call.get("result"), dict) or "ok" not in call.get("result", {})
        ]
        checks.append(
            CheckResult(
                name="structured_tool_results",
                ok=not malformed,
                detail=f"non-structured tool results for {malformed}",
            )
        )
    for snippet in spec.required_text:
        checks.append(
            CheckResult(
                name=f"text:{snippet}",
                ok=snippet.lower() in answer_lower,
                detail=f"answer did not contain '{snippet}'",
            )
        )
    for number in spec.required_numbers:
        matched = any(abs(actual - number) <= spec.number_tolerance for actual in actual_numbers)
        checks.append(
            CheckResult(
                name=f"number:{number}",
                ok=matched,
                detail=f"answer numbers {actual_numbers} did not match {number}±{spec.number_tolerance}",
            )
        )
    return checks


def evaluate_turn_payload(spec: ReplayTurnSpec, payload: dict[str, Any]) -> list[CheckResult]:
    checks = evaluate_payload(
        ReplaySpec(
            case_id=spec.turn_id,
            question=spec.question,
            expected_intent_types=spec.expected_intent_types,
            required_tools=spec.required_tools,
            required_bound_tools=spec.required_bound_tools,
            required_trace_kinds=spec.required_trace_kinds,
            required_text=spec.required_text,
            required_numbers=spec.required_numbers,
            number_tolerance=spec.number_tolerance,
            expected_stop_reason=spec.expected_stop_reason,
            require_structured_tool_results=spec.require_structured_tool_results,
        ),
        payload,
    )
    verdict = payload.get("prior_answer_verdict")
    if spec.require_prior_answer_verdict:
        checks.append(
            CheckResult(
                name="prior_answer_verdict:present",
                ok=isinstance(verdict, dict),
                detail=f"expected structured prior_answer_verdict, got {type(verdict).__name__}",
            )
        )
    if isinstance(verdict, dict):
        verdict_text = json.dumps(verdict, sort_keys=True).lower()
        verdict_numbers = extract_numbers_from_value(verdict)
        for snippet in spec.required_prior_answer_verdict_text:
            checks.append(
                CheckResult(
                    name=f"prior_answer_verdict:text:{snippet}",
                    ok=snippet.lower() in verdict_text,
                    detail=f"prior_answer_verdict did not contain '{snippet}'",
                )
            )
        for number in spec.required_prior_answer_verdict_numbers:
            matched = any(abs(actual - number) <= spec.number_tolerance for actual in verdict_numbers)
            checks.append(
                CheckResult(
                    name=f"prior_answer_verdict:number:{number}",
                    ok=matched,
                    detail=(
                        f"prior_answer_verdict numbers {verdict_numbers} "
                        f"did not match {number}±{spec.number_tolerance}"
                    ),
                )
            )
    return checks


def _create_session(base_url: str, title: str) -> str:
    body = json.dumps({"title": title}).encode()
    req = request.Request(
        f"{base_url.rstrip('/')}/api/sessions",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(req) as resp:
        return json.loads(resp.read().decode())["id"]


def _post_question(base_url: str, *, session_id: str, question: str, gating_mode: str) -> dict[str, Any]:
    body = json.dumps({
        "question": question,
        "gating_mode": gating_mode,
        "session_id": session_id,
    }).encode()
    req = request.Request(
        f"{base_url.rstrip('/')}/api/chat",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(req) as resp:
        return json.loads(resp.read().decode())


def run_case(base_url: str, spec: ReplaySpec, gating_mode: str = "gated") -> dict[str, Any]:
    session_id = _create_session(base_url, f"Replay {spec.case_id}")
    return _post_question(base_url, session_id=session_id, question=spec.question, gating_mode=gating_mode)


def run_multi_turn_case(
    base_url: str,
    spec: MultiTurnReplaySpec,
    gating_mode: str = "gated",
) -> list[tuple[ReplayTurnSpec, dict[str, Any]]]:
    session_id = _create_session(base_url, f"Replay {spec.transcript_id}")
    results: list[tuple[ReplayTurnSpec, dict[str, Any]]] = []
    for turn in spec.turns:
        payload = _post_question(
            base_url,
            session_id=session_id,
            question=turn.question,
            gating_mode=gating_mode,
        )
        results.append((turn, payload))
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog=".venv/bin/python -m app.case_replay",
        description="Replay oracle-backed cases through the chat API and validate intent/tool/answer checks.",
    )
    parser.add_argument("--server", default="http://127.0.0.1:9006", help="server base URL")
    parser.add_argument("--gating-mode", choices=["gated", "bind_all"], default="gated")
    parser.add_argument("--case", action="append", default=[], help="case id to replay; repeatable")
    parser.add_argument(
        "--transcript",
        action="append",
        default=[],
        help="multi-turn transcript id to replay; repeatable",
    )
    args = parser.parse_args(argv)

    build_oracle()  # validates the oracle can be built before replay
    specs = build_replay_specs()
    multi_turn_specs = build_multi_turn_specs()
    selected_ids = args.case or list(specs)
    rc = 0
    for case_id in selected_ids:
        if case_id not in specs:
            print(f"{case_id}: unknown case id")
            rc = 1
            continue
        spec = specs[case_id]
        payload = run_case(args.server, spec, gating_mode=args.gating_mode)
        checks = evaluate_payload(spec, payload)
        ok = all(check.ok for check in checks)
        print(f"{case_id}: {'PASS' if ok else 'FAIL'}")
        print(f"  question: {spec.question}")
        print(f"  intent: {payload.get('intent', {}).get('types', [])}")
        print(f"  tools: {[call.get('name') for call in payload.get('tool_calls', [])]}")
        for check in checks:
            print(f"  - {check.name}: {'ok' if check.ok else 'fail'} ({check.detail})")
        if not ok:
            rc = 1
    selected_transcripts = args.transcript or []
    for transcript_id in selected_transcripts:
        if transcript_id not in multi_turn_specs:
            print(f"{transcript_id}: unknown transcript id")
            rc = 1
            continue
        transcript = multi_turn_specs[transcript_id]
        turn_results = run_multi_turn_case(args.server, transcript, gating_mode=args.gating_mode)
        transcript_ok = True
        print(f"{transcript.transcript_id}: {transcript.title}")
        for turn, payload in turn_results:
            checks = evaluate_turn_payload(turn, payload)
            ok = all(check.ok for check in checks)
            transcript_ok = transcript_ok and ok
            print(f"  {turn.turn_id}: {'PASS' if ok else 'FAIL'}")
            print(f"    question: {turn.question}")
            print(f"    intent: {payload.get('intent', {}).get('types', [])}")
            print(f"    tools: {[call.get('name') for call in payload.get('tool_calls', [])]}")
            if turn.deferred_assertions:
                print(f"    deferred_assertions: {list(turn.deferred_assertions)}")
            for check in checks:
                print(f"    - {check.name}: {'ok' if check.ok else 'fail'} ({check.detail})")
        if not transcript_ok:
            rc = 1
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
