"""Replay harness for CLI/API case validation against the oracle."""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from typing import Any
from urllib import request

from scripts.golden_answers import build as build_oracle


@dataclass(frozen=True)
class ReplaySpec:
    case_id: str
    question: str
    expected_intent_types: tuple[str, ...]
    required_tools: tuple[str, ...] = ()
    required_bound_tools: tuple[str, ...] = ()
    required_trace_kinds: tuple[str, ...] = ()
    required_text: tuple[str, ...] = ()
    required_numbers: tuple[float, ...] = ()
    number_tolerance: float = 0.05
    expected_stop_reason: str = "final_answer"
    require_structured_tool_results: bool = False


@dataclass(frozen=True)
class CheckResult:
    name: str
    ok: bool
    detail: str


def build_replay_specs() -> dict[str, ReplaySpec]:
    return {
        "D2": ReplaySpec(
            case_id="D2",
            question="What was the average daily yield of Rajasthan Solar Park last week?",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(123354.2,),
        ),
        "D3": ReplaySpec(
            case_id="D3",
            question="Which inverters have open hotspot anomalies caused by soiling?",
            expected_intent_types=("C",),
            required_tools=("anomalies",),
            required_text=("hotspot", "soiling"),
            required_numbers=(2.0, 7.0, 55.0),
        ),
        "D4": ReplaySpec(
            case_id="D4",
            question="What is the mean time to resolve a critical alert?",
            expected_intent_types=("B",),
            required_numbers=(6.3, 6.0),
        ),
        "D5": ReplaySpec(
            case_id="D5",
            question="What's the weather like at the Gujarat plant today?",
            expected_intent_types=("A", "B"),
            required_text=("gujarat",),
            required_numbers=(26.04, 46.24, 799.34),
        ),
        "D6": ReplaySpec(
            case_id="D6",
            question="How much revenue did we lose from Tamil Nadu's downtime this month?",
            expected_intent_types=(),
            required_text=("can't answer", "dataset"),
            expected_stop_reason="out_of_scope",
        ),
        "P4": ReplaySpec(
            case_id="P4",
            question="Which plant has the highest feed-in tariff?",
            expected_intent_types=("B",),
            required_bound_tools=("inverters", "plants"),
            required_text=("rajasthan",),
            required_numbers=(0.052,),
        ),
        "I5": ReplaySpec(
            case_id="I5",
            question='Show inverters that are "online" in status but have an open alert.',
            expected_intent_types=("A",),
            required_text=("inv_4135001_05",),
            required_numbers=(4.0,),
        ),
        "G2": ReplaySpec(
            case_id="G2",
            question="Total energy generated by Rajasthan this month.",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(3004224.3,),
        ),
        "G4": ReplaySpec(
            case_id="G4",
            question="Which inverter tops the fleet on performance ratio?",
            expected_intent_types=("B",),
            required_text=("inv_4137001_04",),
            required_numbers=(0.9519,),
        ),
        "W3": ReplaySpec(
            case_id="W3",
            question="Which plant had the highest cloud cover this month?",
            expected_intent_types=("B",),
            required_text=("rajasthan",),
            required_numbers=(23.66,),
        ),
        "AL5": ReplaySpec(
            case_id="AL5",
            question="Mean time to resolve an alert, all severities.",
            expected_intent_types=("B",),
            required_numbers=(22.16, 25.0),
        ),
        "AN6": ReplaySpec(
            case_id="AN6",
            question="Give me a rundown of every unresolved anomaly at Rajasthan Solar Park.",
            expected_intent_types=("C",),
            required_bound_tools=("anomalies", "inverters", "plants"),
            required_trace_kinds=("intent_finished", "synthesis_started", "model_invoke_started"),
            required_text=("rajasthan",),
            required_numbers=(15.0, 7.0, 5.0, 3.0),
            require_structured_tool_results=True,
        ),
        "X2": ReplaySpec(
            case_id="X2",
            question="Compare Rajasthan and Tamil Nadu on open anomalies and yield.",
            expected_intent_types=("B", "C"),
            required_text=("rajasthan", "tamil"),
            required_numbers=(7.0, 13.0, 123354.2, 151152.5),
        ),
        "X4": ReplaySpec(
            case_id="X4",
            question="Which plant is performing worst right now?",
            expected_intent_types=("B",),
            required_bound_tools=("performance_ratio", "inverters", "plants"),
            required_text=("rajasthan",),
            required_numbers=(0.9077,),
        ),
        "X6": ReplaySpec(
            case_id="X6",
            question="How is the plant doing?",
            expected_intent_types=(),
            required_text=("which plant",),
        ),
    }


def extract_numbers(text: str) -> list[float]:
    return [float(match.replace(",", "")) for match in re.findall(r"-?\d[\d,]*\.?\d*", text)]


def contains_subsequence(actual: list[str], required: tuple[str, ...]) -> bool:
    if not required:
        return True
    index = 0
    for item in actual:
        if item == required[index]:
            index += 1
            if index == len(required):
                return True
    return False


def evaluate_payload(spec: ReplaySpec, payload: dict[str, Any]) -> list[CheckResult]:
    answer = str(payload.get("answer", ""))
    answer_lower = answer.lower()
    tool_names = [str(call.get("name", "")) for call in payload.get("tool_calls", [])]
    bound_tools = [str(name) for name in payload.get("bound_tools", [])]
    trace_kinds = [str(event.get("kind", "")) for event in payload.get("trace_events", [])]
    actual_types = tuple(str(v) for v in payload.get("intent", {}).get("types", []))
    actual_numbers = extract_numbers(answer)

    checks = [
        CheckResult(
            name="stop_reason",
            ok=str(payload.get("stop_reason", "")) == spec.expected_stop_reason,
            detail=f"expected {spec.expected_stop_reason}, got {payload.get('stop_reason', '')}",
        ),
        CheckResult(
            name="intent_types",
            ok=all(intent_type in actual_types for intent_type in spec.expected_intent_types),
            detail=f"expected at least {list(spec.expected_intent_types)}, got {list(actual_types)}",
        ),
        CheckResult(
            name="tool_chain",
            ok=contains_subsequence(tool_names, spec.required_tools),
            detail=f"expected subsequence {list(spec.required_tools)}, got {tool_names}",
        ),
        CheckResult(
            name="bound_tools",
            ok=contains_subsequence(bound_tools, spec.required_bound_tools),
            detail=f"expected subsequence {list(spec.required_bound_tools)}, got {bound_tools}",
        ),
        CheckResult(
            name="trace_kinds",
            ok=contains_subsequence(trace_kinds, spec.required_trace_kinds),
            detail=f"expected subsequence {list(spec.required_trace_kinds)}, got {trace_kinds}",
        ),
    ]
    if spec.require_structured_tool_results:
        malformed = [
            str(call.get("name", ""))
            for call in payload.get("tool_calls", [])
            if not isinstance(call.get("result"), dict) or "ok" not in call.get("result", {})
        ]
        checks.append(
            CheckResult(
                name="structured_tool_results",
                ok=not malformed,
                detail=f"non-structured tool results for {malformed}",
            )
        )
    for snippet in spec.required_text:
        checks.append(
            CheckResult(
                name=f"text:{snippet}",
                ok=snippet.lower() in answer_lower,
                detail=f"answer did not contain '{snippet}'",
            )
        )
    for number in spec.required_numbers:
        matched = any(abs(actual - number) <= spec.number_tolerance for actual in actual_numbers)
        checks.append(
            CheckResult(
                name=f"number:{number}",
                ok=matched,
                detail=f"answer numbers {actual_numbers} did not match {number}±{spec.number_tolerance}",
            )
        )
    return checks


def _create_session(base_url: str, title: str) -> str:
    body = json.dumps({"title": title}).encode()
    req = request.Request(
        f"{base_url.rstrip('/')}/api/sessions",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(req) as resp:
        return json.loads(resp.read().decode())["id"]


def run_case(base_url: str, spec: ReplaySpec, gating_mode: str = "gated") -> dict[str, Any]:
    session_id = _create_session(base_url, f"Replay {spec.case_id}")
    body = json.dumps({
        "question": spec.question,
        "gating_mode": gating_mode,
        "session_id": session_id,
    }).encode()
    req = request.Request(
        f"{base_url.rstrip('/')}/api/chat",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(req) as resp:
        return json.loads(resp.read().decode())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog=".venv/bin/python -m app.case_replay",
        description="Replay oracle-backed cases through the chat API and validate intent/tool/answer checks.",
    )
    parser.add_argument("--server", default="http://127.0.0.1:9006", help="server base URL")
    parser.add_argument("--gating-mode", choices=["gated", "bind_all"], default="gated")
    parser.add_argument("--case", action="append", default=[], help="case id to replay; repeatable")
    args = parser.parse_args(argv)

    build_oracle()  # validates the oracle can be built before replay
    specs = build_replay_specs()
    selected_ids = args.case or list(specs)
    rc = 0
    for case_id in selected_ids:
        if case_id not in specs:
            print(f"{case_id}: unknown case id")
            rc = 1
            continue
        spec = specs[case_id]
        payload = run_case(args.server, spec, gating_mode=args.gating_mode)
        checks = evaluate_payload(spec, payload)
        ok = all(check.ok for check in checks)
        print(f"{case_id}: {'PASS' if ok else 'FAIL'}")
        print(f"  question: {spec.question}")
        print(f"  intent: {payload.get('intent', {}).get('types', [])}")
        print(f"  tools: {[call.get('name') for call in payload.get('tool_calls', [])]}")
        for check in checks:
            print(f"  - {check.name}: {'ok' if check.ok else 'fail'} ({check.detail})")
        if not ok:
            rc = 1
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
